/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snakenladder.objects;

import java.awt.Color;

/**
 *
 * @author bayasys
 */
public class playertabSmall extends javax.swing.JPanel {

    /**
     * Creates new form playertab
     */
    public playertabSmall(player pl) {
        initComponents();
        pnl_clr.setBackground(pl.getColor());
        lbl_palyerName.setText(pl.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_palyerName = new javax.swing.JLabel();
        pnl_clr = new javax.swing.JPanel();

        setBackground(new java.awt.Color(84, 77, 77));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(250, 40));
        setMinimumSize(new java.awt.Dimension(250, 40));
        setPreferredSize(new java.awt.Dimension(250, 40));

        lbl_palyerName.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lbl_palyerName.setForeground(new java.awt.Color(246, 180, 180));
        lbl_palyerName.setText("Player");

        pnl_clr.setBackground(new java.awt.Color(242, 29, 29));

        javax.swing.GroupLayout pnl_clrLayout = new javax.swing.GroupLayout(pnl_clr);
        pnl_clr.setLayout(pnl_clrLayout);
        pnl_clrLayout.setHorizontalGroup(
            pnl_clrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        pnl_clrLayout.setVerticalGroup(
            pnl_clrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_palyerName, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_clr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_palyerName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(pnl_clr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_palyerName;
    private javax.swing.JPanel pnl_clr;
    // End of variables declaration//GEN-END:variables
}
